<?php 
    $redis = new Redis();
    $redis->connect('127.0.0.1',6379);
    $docid = $redis-.get("loginid");
    $conn = new mysqli("localhost","root","","guvi");
     $stmt = $conn->prepare("SELECT * FROM Login WHERE email = ?");
        $stmt->bind_param("s", $email);
        $email = $cred->email;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE fname = ?");
        $stmt->bind_param("s", $fname);
        $fname = $cred->fname;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE dob = ?");
        $stmt->bind_param("s", $dob);
        $dob = $cred->dob;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE gender = ?");
        $stmt->bind_param("s", $gender);
        $gender = $cred->gender;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE dept = ?");
        $stmt->bind_param("s", $dept);
        $dept = $cred->dept;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE desig = ?");
        $stmt->bind_param("s", $desig);
        $desig = $cred->desig;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE address1 = ?");
        $stmt->bind_param("s", $address1);
        $address1 = $cred->address;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE city = ?");
        $stmt->bind_param("s", $city);
        $city = $cred->city;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE state1 = ?");
        $stmt->bind_param("s", $state1);
        $state1 = $cred->state;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE phone = ?");
        $stmt->bind_param("s", $phone);
        $phone = $cred->phone;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE zip = ?");
        $stmt->bind_param("s", $zip);
        $zip = $cred->zip;
        $stmt->execute();
        
        $result = $stmt->get_result();
        $resultset = $result->fetch_assoc();
        echo 1;
    echo "<script>\n";
    echo " let doc = ".$resultset;
    echo "</script>";
    include(__DIR__."\..\profile.html");
?>